#
# Module manifest for module 'PowerVCF'
#
# Generated by: Brian O Connell
#
# Generated on: 31/05/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerVCF.psm1'

# Version number of this module.
ModuleVersion = '2.1.8'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '08d28c56-f241-4a8c-8806-dee337cf74c9'

# Author of this module
Author = 'Brian O Connell, Gary Blake & Ken Gould'

# Description of the functionality provided by this module
Description = 'PowerShell Module for the VMware Cloud Foundation 4.x API.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @('')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

}
