---
blank_issues_enabled: false
contact_links:
  - name: Module Documentation
    url: 'https://vmware.github.io/powershell-module-for-vmware-cloud-foundation'
    about: Having trouble with the module? Check out the documentation.
  - name: VMware Cloud Foundation Documentation
    url: 'https://docs.vmware.com/en/VMware-Cloud-Foundation/'
    about: Having trouble with VMware Cloud Foundation? Check out the product documentation.
